### ISSUE TITLE
Updated blocklist?

### ISSUE THREAD

**Issue by geekgonecrazy** [masto-donte-com-br/InstanceInternals#4]
@renatolond Curious if this is the updated block list?

https://fosstodon.org/@geekgonecrazy/103689761389582548

It looks like fosstodon might be blocked both by the instance and by the cross poster?

**Comment by renatolond** [comment]
Hey, we don't update this list anymore since Mastodon got the ability to list the blocks internally. But yeah, fosstodon is blocked.

**Comment by geekgonecrazy** [comment]
Thanks for the confirmation.  Any particular reason?  Any content or changes that can be made?  I’ve been in contact with the admins of the server and they also aren’t aware of what happened or why they are on a block list.

I understand blocking an instance because an incident arises.  But would hope there is a way to resolve the issue.
